services:
  payload:
    image: node:22-alpine
    ports:
      - '3003:3003'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install && npm run dev"
    depends_on:
      - postgres
    env_file:
      - .env

  # Using Postgres as the database. Example DATABASE_URI:
  #   postgres://postgres:postgres@postgres:5432/gagik

  # Uncomment the following to use postgres
  postgres:
    restart: always
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gagik
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata:
  node_modules:
